# Generated by Django 5.0.1 on 2024-01-26 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_faturas', '0002_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faturas_cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app_faturas.cliente')),
            ],
        ),
    ]
