# Generated by Django 5.0.1 on 2024-01-28 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_faturas', '0002_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='pessoa',
        ),
    ]
