# Generated by Django 5.0.1 on 2024-02-01 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_faturas', '0004_compra_data_delete_fatura'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='ano',
            field=models.IntegerField(default=2024),
        ),
        migrations.AddField(
            model_name='compra',
            name='mes',
            field=models.IntegerField(default=2),
        ),
    ]
