# Generated by Django 5.0.1 on 2024-02-02 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_faturas', '0005_compra_ano_compra_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='ano',
            field=models.IntegerField(default=2024, editable=False),
        ),
        migrations.AlterField(
            model_name='compra',
            name='mes',
            field=models.IntegerField(default=2, editable=False),
        ),
    ]
